# CONFIGURATION FILE

# This file is used to pass information down to the build process and
# templating engine. You don't need to mess with any other files in the `src`
# folder; just change this and we'll spit out a simple website for you.

# theme: mono # Comment this out if you want to change the theme
# distFolder: dist # Comment this out if you want a custom dist folder

templateLocals:
  name: Handshake
  title: A minimalist one-page generator for freelancers.
  description: A minimalist one-page generator for freelancers.
  text:
    heading: Generate a one-page hub in minutes.
    body: This is **Handshake**, crafted to be a quick solution for redirecting your clients/contacts to your other content & social media. It's super easy to set up, built with GitHub Pages in mind, features 5 color themes and icons from FontAwesome. Oh, and this body of text even supports Markdown.
  icons:
    - id: github
      url: https://www.github.com/joaobelve/handshake
      title: Fork it on GitHub
    - id: twitter
      url: https://twitter.com/joaobelve
      title: Tweet @joaobelve
    - id: medium
      url: https://medium.com/@joaobelve
      title: Follow @joaobelve on Medium
    - id: instagram
      url: https://www.instagram.com/joaobelve/
      title: Follow @joaobelve on Instagram
